FROM ubuntu

# Install packages
RUN apt install dovecot-core \
                dovecot-imapd \
                dovecot-managesieved \
                dovecot-pop3d \
                postfix \
                opendkim \
                opendkim-tools \
                spamass-milter \
                pyzor \
                razor \
                libmail-dkim-perl \
                clamav-milter \
                arj \
                bzip2 \
                cabextract \
                cpio \
                file \
                gzip \
                lha \
                lzop \
                nomarch \
                p7zip \
                pax \
                rar \
                rpm \
                unrar \
                unzip \
                zip \
                zoo \
                iptables-persistent && \

# Copy source
COPY root/ /

# Configure postfix
RUN postconf -e "myhostname = ${SERVER_HOSTNAME}" \
                "mydestination = $myhostname, localhost.${SERVER_HOSTNAME}, localhost" \
                "smtpd_tls_cert_file = /config/ssl/ssl-cert-${SERVER_HOSTNAME}.pem" \
                "smtpd_tls_key_file = /config/ssl/ssl-key-${SERVER_HOSTNAME}.key" && \

# Set postfix maps
    echo "postmaster: webmaster@${SERVER_HOSTNAME}
root: webmaster@${SERVER_HOSTNAME}
www-data: webmaster@${SERVER_HOSTNAME}" > /etc/aliases && \

    echo "www-data@${SERVER_HOSTNAME} mailman@${SERVER_HOSTNAME}" > /etc/postfix/canonical && \

    echo "${SERVER_HOSTNAME}      OK" > /etc/postfix/virtual-mailbox-domains && \

    echo "sascha@${SERVER_HOSTNAME}		sascha@${SERVER_HOSTNAME}
mailman@${SERVER_HOSTNAME}	mailman@${SERVER_HOSTNAME}
webmaster@${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}" > /etc/postfix/virtual-mailbox-users && \

    echo "sascha@${SERVER_HOSTNAME}		sascha@${SERVER_HOSTNAME}
mailman@${SERVER_HOSTNAME}	mailman@${SERVER_HOSTNAME}
webmaster@${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}
postmaster@${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}
root@mail.${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}
root@${SERVER_HOSTNAME}		webmaster@${SERVER_HOSTNAME}
abuse@${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}
hostmaster@${SERVER_HOSTNAME}	webmaster@${SERVER_HOSTNAME}" > /etc/postfix/virtual && \

# Hash the maps
    newaliases && \
    postmap /etc/postfix/canonical && \
    postmap /etc/postfix/virtual-mailbox-domains && \
    postmap /etc/postfix/virtual-mailbox-users && \
    postmap /etc/postfix/virtual && \

# Add vmail user
    groupadd -g 5000 vmail && \
    useradd -g vmail -u 5000 vmail -d /var/mail/vmail -m && \

# Configure dovecot
    echo "ssl_cert = </config/ssl/ssl-cert-${SERVER_HOSTNAME}.pem
ssl_key = </config/ssl/ssl-key-${SERVER_HOSTNAME}.key
protocol lmtp {
        postmaster_address = postmaster@${SERVER_HOSTNAME}
        mail_plugins = sieve
}" > /etc/dovecot/conf.d/99-mail-stack-delivery-conf && \

# Configure opendkim
    echo "mail.${SERVER_HOSTNAME} mail.${SERVER_HOSTNAME}:mail:/etc/opendkim/mail" > /etc/opendkim/KeyTable && \
    echo "*@${SERVER_HOSTNAME} mail.${SERVER_HOSTNAME}" > /etc/opendkim/SigningTable && \
    chown -R opendkim:opendkim /etc/opendkim && \
    mkdir /var/spool/postfix/opendkim && \
    chown opendkim:root /var/spool/postfix/opendkim && \
    usermod -G opendkim postfix && \

# Configure spamass
    adduser --shell /bin/false --home /var/lib/spamassassin --disabled-password --disabled-login --gecos "" spamd && \
    usermod -a -G spamd spamass-milter && \
